[project]
name = "mlops-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lightning>=2.5.5",
    "transformers>=4.57.0",
]
